import React, { ReactNode } from "react";
import { Inter } from 'next/font/google';
import Link from "next/link";

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Next Blog MD',
    description: 'Generated by create next app',
};

export default function RootLayout ({ children }: {
	children: ReactNode
}) {
    const header = (
        <header>
            <div className="text-center bg-black p-8 my-6 rounded-md">
                <Link href={"/"}>
                    <h1 className="text-blue-500 text-3xl font-bold">
                        NextJS Blog
                    </h1>
                </Link>
                <p className="text-white">Welcome!</p>
            </div>
        </header>
    );

    const footer = (
        <footer>
            <div className="text-center bg-black text-white p-4 my-4 rounded-md">
                <p>Next JS</p>
            </div>
        </footer>
    );

    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body>
                <div className="mx-auto max-w-2xl">
                    {header}
                    {children}
                    {footer}
                </div>
            </body>
        </html>
    );
}
